In [2]:
import pandas as pd
import numpy as np
import glob

# Path to the "washing" folder containing all CSV files
file_paths = glob.glob(r"C:\Users\ashut\fedAR\tracebase\complete\Washingmachine\*.csv")

# Load and concatenate all CSV files
data_frames = []
for file in file_paths:
    # Read the entire file content as a single string
    with open(file, 'r') as f:
        file_content = f.read()

    # Split the content by newline to get individual rows
    rows = file_content.split('\n')

    # Create a DataFrame from the rows
    df = pd.DataFrame(rows, columns=['data'])
    data_frames.append(df)

# Concatenate all files
merged_df0 = pd.concat(data_frames, ignore_index=True)

# Split the single column into 'datetime', 'info1', and 'info2'
merged_df0[['datetime', 'info1', 'info2']] = merged_df0['data'].str.split(';', expand=True)

# Drop the original 'data' column
merged_df0.drop(columns=['data'], inplace=True)

# Convert datetime to proper datetime format
merged_df0['datetime'] = pd.to_datetime(merged_df0['datetime'], format='%d/%m/%Y %H:%M:%S', errors='coerce')

print(merged_df0.head())
print(f"Merged DataFrame shape: {merged_df0.shape}")

             datetime info1 info2
0 2011-12-03 01:00:03     0     0
1 2011-12-03 01:00:06     0     0
2 2011-12-03 01:00:10     0     0
3 2011-12-03 01:00:13     0     0
4 2011-12-03 01:00:16     0     0
Merged DataFrame shape: (2024537, 3)


In [3]:
merged_df0['appliance'] = 0

# Display the updated DataFrame
print(merged_df0.head())

             datetime info1 info2  appliance
0 2011-12-03 01:00:03     0     0          0
1 2011-12-03 01:00:06     0     0          0
2 2011-12-03 01:00:10     0     0          0
3 2011-12-03 01:00:13     0     0          0
4 2011-12-03 01:00:16     0     0          0


In [4]:
count= merged_df0.isna().sum()
count

datetime     54
info1        54
info2        54
appliance     0
dtype: int64

In [5]:
merged_df0= merged_df0.dropna()
merged_df0.shape

(2024483, 4)

In [6]:
# Path to the "washing" folder containing all CSV files
file_paths = glob.glob(r"C:\Users\ashut\fedAR\tracebase\complete\Dishwasher\*.csv")

# Load and concatenate all CSV files
data_frames = []
for file in file_paths:
    # Read the entire file content as a single string
    with open(file, 'r') as f:
        file_content = f.read()

    # Split the content by newline to get individual rows
    rows = file_content.split('\n')

    # Create a DataFrame from the rows
    df = pd.DataFrame(rows, columns=['data'])
    data_frames.append(df)

# Concatenate all files
merged_df1 = pd.concat(data_frames, ignore_index=True)

# Split the single column into 'datetime', 'info1', and 'info2'
merged_df1[['datetime', 'info1', 'info2']] = merged_df1['data'].str.split(';', expand=True)

# Drop the original 'data' column
merged_df1.drop(columns=['data'], inplace=True)

# Convert datetime to proper datetime format
merged_df1['datetime'] = pd.to_datetime(merged_df1['datetime'], format='%d/%m/%Y %H:%M:%S', errors='coerce')

print(merged_df1.head())
print(f"Merged DataFrame shape: {merged_df1.shape}")

             datetime info1 info2
0 2012-06-11 00:00:01     0     0
1 2012-06-11 00:00:02     0     0
2 2012-06-11 00:00:03     0     0
3 2012-06-11 00:00:04     0     0
4 2012-06-11 00:00:05     0     0
Merged DataFrame shape: (5716354, 3)


In [7]:
merged_df1['appliance'] = 1

# Display the updated DataFrame
print(merged_df1.head())

             datetime info1 info2  appliance
0 2012-06-11 00:00:01     0     0          1
1 2012-06-11 00:00:02     0     0          1
2 2012-06-11 00:00:03     0     0          1
3 2012-06-11 00:00:04     0     0          1
4 2012-06-11 00:00:05     0     0          1


In [8]:
merged_df1= merged_df1.dropna()
merged_df1.shape

(5716278, 4)

In [9]:
# Path to the "washing" folder containing all CSV files
file_paths = glob.glob(r"C:\Users\ashut\fedAR\tracebase\complete\Amplifier\*.csv")

# Load and concatenate all CSV files
data_frames = []
for file in file_paths:
    # Read the entire file content as a single string
    with open(file, 'r') as f:
        file_content = f.read()

    # Split the content by newline to get individual rows
    rows = file_content.split('\n')

    # Create a DataFrame from the rows
    df = pd.DataFrame(rows, columns=['data'])
    data_frames.append(df)

# Concatenate all files
merged_df2 = pd.concat(data_frames, ignore_index=True)

# Split the single column into 'datetime', 'info1', and 'info2'
merged_df2[['datetime', 'info1', 'info2']] = merged_df2['data'].str.split(';', expand=True)

# Drop the original 'data' column
merged_df2.drop(columns=['data'], inplace=True)

# Convert datetime to proper datetime format
merged_df2['datetime'] = pd.to_datetime(merged_df2['datetime'], format='%d/%m/%Y %H:%M:%S', errors='coerce')

print(merged_df2.head())
print(f"Merged DataFrame shape: {merged_df2.shape}")

             datetime info1 info2
0 2012-01-25 00:00:01     0     0
1 2012-01-25 00:00:04     0     0
2 2012-01-25 00:00:06     0     0
3 2012-01-25 00:00:10     0     0
4 2012-01-25 00:00:15     0     0
Merged DataFrame shape: (3399729, 3)


In [10]:
merged_df2['appliance'] = 2

# Display the updated DataFrame
print(merged_df2.head())

             datetime info1 info2  appliance
0 2012-01-25 00:00:01     0     0          2
1 2012-01-25 00:00:04     0     0          2
2 2012-01-25 00:00:06     0     0          2
3 2012-01-25 00:00:10     0     0          2
4 2012-01-25 00:00:15     0     0          2


In [11]:
merged_df2= merged_df2.dropna()
merged_df2.shape

(3399640, 4)

In [12]:
# Path to the "washing" folder containing all CSV files
file_paths = glob.glob(r"C:\Users\ashut\fedAR\tracebase\complete\Refrigerator\*.csv")

# Load and concatenate all CSV files
data_frames = []
for file in file_paths:
    # Read the entire file content as a single string
    with open(file, 'r') as f:
        file_content = f.read()

    # Split the content by newline to get individual rows
    rows = file_content.split('\n')

    # Create a DataFrame from the rows
    df = pd.DataFrame(rows, columns=['data'])
    data_frames.append(df)

# Concatenate all files
merged_df3 = pd.concat(data_frames, ignore_index=True)

# Split the single column into 'datetime', 'info1', and 'info2'
merged_df3[['datetime', 'info1', 'info2']] = merged_df3['data'].str.split(';', expand=True)

# Drop the original 'data' column
merged_df3.drop(columns=['data'], inplace=True)

# Convert datetime to proper datetime format
merged_df3['datetime'] = pd.to_datetime(merged_df3['datetime'], format='%d/%m/%Y %H:%M:%S', errors='coerce')

print(merged_df3.head())
print(f"Merged DataFrame shape: {merged_df3.shape}")

             datetime info1 info2
0 2012-01-08 00:00:02   136   134
1 2012-01-08 00:00:03   134   134
2 2012-01-08 00:00:05   136   134
3 2012-01-08 00:00:06   136   134
4 2012-01-08 00:00:08   134   134
Merged DataFrame shape: (14643997, 3)


In [13]:
merged_df3['appliance'] = 3

# Display the updated DataFrame
print(merged_df3.head())

             datetime info1 info2  appliance
0 2012-01-08 00:00:02   136   134          3
1 2012-01-08 00:00:03   134   134          3
2 2012-01-08 00:00:05   136   134          3
3 2012-01-08 00:00:06   136   134          3
4 2012-01-08 00:00:08   134   134          3


In [14]:
merged_df3= merged_df3.dropna()
merged_df3.shape

(14643792, 4)

In [15]:

rows_to_drop = merged_df3.sample(n=10600000, random_state=42).index

# Drop the selected rows
merged_df3 = merged_df3.drop(index=rows_to_drop)

# Display the updated DataFrame
print(merged_df3.shape)  # Should now have 5000 fewer rows
print(merged_df3.head())

(4043792, 4)
              datetime info1 info2  appliance
1  2012-01-08 00:00:03   134   134          3
4  2012-01-08 00:00:08   134   134          3
19 2012-01-08 00:00:29   134   132          3
20 2012-01-08 00:00:31   134   132          3
21 2012-01-08 00:00:32   132   132          3


In [16]:
# Path to the "washing" folder containing all CSV files
file_paths = glob.glob(r"C:\Users\ashut\fedAR\tracebase\complete\PC-Laptop\*.csv")

# Load and concatenate all CSV files
data_frames = []
for file in file_paths:
    # Read the entire file content as a single string
    with open(file, 'r') as f:
        file_content = f.read()

    # Split the content by newline to get individual rows
    rows = file_content.split('\n')

    # Create a DataFrame from the rows
    df = pd.DataFrame(rows, columns=['data'])
    data_frames.append(df)

# Concatenate all files
merged_df4 = pd.concat(data_frames, ignore_index=True)

# Split the single column into 'datetime', 'info1', and 'info2'
merged_df4[['datetime', 'info1', 'info2']] = merged_df4['data'].str.split(';', expand=True)

# Drop the original 'data' column
merged_df4.drop(columns=['data'], inplace=True)

# Convert datetime to proper datetime format
merged_df4['datetime'] = pd.to_datetime(merged_df4['datetime'], format='%d/%m/%Y %H:%M:%S', errors='coerce')

print(merged_df4.head())
print(f"Merged DataFrame shape: {merged_df4.shape}")

             datetime info1 info2
0 2012-01-18 00:00:00     0     0
1 2012-01-18 00:00:01     0     0
2 2012-01-18 00:00:03     0     0
3 2012-01-18 00:00:04     0     0
4 2012-01-18 00:00:06     0     0
Merged DataFrame shape: (2413417, 3)


In [17]:
merged_df4['appliance'] = 4

# Display the updated DataFrame
print(merged_df4.head())

             datetime info1 info2  appliance
0 2012-01-18 00:00:00     0     0          4
1 2012-01-18 00:00:01     0     0          4
2 2012-01-18 00:00:03     0     0          4
3 2012-01-18 00:00:04     0     0          4
4 2012-01-18 00:00:06     0     0          4


In [18]:
merged_df4= merged_df4.dropna()
merged_df4.shape

(2413352, 4)

In [31]:

final_df = pd.concat([merged_df0, merged_df1, merged_df2, merged_df3, merged_df4], ignore_index=True)

# Display the result
print(final_df.head())
print(f"Final DataFrame shape: {final_df.shape}")

             datetime info1 info2  appliance
0 2011-12-03 01:00:03     0     0          0
1 2011-12-03 01:00:06     0     0          0
2 2011-12-03 01:00:10     0     0          0
3 2011-12-03 01:00:13     0     0          0
4 2011-12-03 01:00:16     0     0          0
Final DataFrame shape: (17597545, 4)


In [32]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Ensure 'datetime' column is in datetime format
final_df['datetime'] = pd.to_datetime(final_df['datetime'])

# Feature engineering
final_df['year'] = final_df['datetime'].dt.year
final_df['month'] = final_df['datetime'].dt.month
final_df['day'] = final_df['datetime'].dt.day
final_df['hour'] = final_df['datetime'].dt.hour
final_df['day_of_week'] = final_df['datetime'].dt.dayofweek

# Cyclic encoding
final_df['hour_sin'] = np.sin(2 * np.pi * final_df['hour'] / 24)
final_df['hour_cos'] = np.cos(2 * np.pi * final_df['hour'] / 24)
final_df['day_of_week_sin'] = np.sin(2 * np.pi * final_df['day_of_week'] / 7)
final_df['day_of_week_cos'] = np.cos(2 * np.pi * final_df['day_of_week'] / 7)

# Lag and rolling features
final_df['info1_lag_1'] = final_df['info1'].shift(1)
final_df['info2_lag_1'] = final_df['info2'].shift(1)
final_df['info1_rolling_mean_3'] = final_df['info1'].rolling(window=3).mean()
final_df['info2_rolling_std_3'] = final_df['info2'].rolling(window=3).std()

# Drop rows with NaN values after creating lag/rolling features
final_df.dropna(inplace=True)

# Scaling
scaler = StandardScaler()
scaled_features = scaler.fit_transform(final_df[['info1', 'info2', 'info1_lag_1', 'info2_lag_1', 'info1_rolling_mean_3', 'info2_rolling_std_3']])
final_df[['info1', 'info2', 'info1_lag_1', 'info2_lag_1', 'info1_rolling_mean_3', 'info2_rolling_std_3']] = scaled_features

# Data split
train_size = int(0.7 * len(final_df))
val_size = int(0.15 * len(final_df))
train, val, test = final_df[:train_size], final_df[train_size:train_size + val_size], final_df[train_size + val_size:]

# Drop original datetime column and separate features and target variable
train, test = train.drop(columns=['datetime']), test.drop(columns=['datetime'])
X_train, y_train = train.drop(columns=['appliance']), train['appliance']
X_test, y_test = test.drop(columns=['appliance']), test['appliance']


In [33]:
X_test.head()

info1     info2  year  month  day  hour  day_of_week  \
14957913 -0.119167 -0.127267  2012      1   10    12            1   
14957914 -0.128706 -0.127267  2012      1   10    12            1   
14957915 -0.119167 -0.127267  2012      1   10    12            1   
14957916 -0.119167 -0.127267  2012      1   10    12            1   
14957917 -0.128706 -0.127267  2012      1   10    12            1   

              hour_sin  hour_cos  day_of_week_sin  day_of_week_cos  \
14957913  1.224647e-16      -1.0         0.781831          0.62349   
14957914  1.224647e-16      -1.0         0.781831          0.62349   
14957915  1.224647e-16      -1.0         0.781831          0.62349   
14957916  1.224647e-16      -1.0         0.781831          0.62349   
14957917  1.224647e-16      -1.0         0.781831          0.62349   

          info1_lag_1  info2_lag_1  info1_rolling_mean_3  info2_rolling_std_3  
14957913    -0.128706    -0.127267             -0.122509            -0.051717  
14957914    -0.119167    -0.127267             -0.125692            -0.051717  
14957915    -0.128706    -0.127267             -0.122509            -0.051717  
14957916    -0.119167    -0.127267             -0.122509            -0.051717  
14957917    -0.119167    -0.127267             -0.122509            -0.051717

In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Further split the dataset if necessary to verify the model behavior
X_sample, _, y_sample, _ = train_test_split(X_train, y_train, train_size=0.1, random_state=42)

model = RandomForestClassifier(n_estimators=10, random_state=42)
model.fit(X_sample, y_sample)

# Check if feature importances are available
if hasattr(model, "feature_importances_"):
    print("Feature Importances:", model.feature_importances_)
else:
    print("Model does not provide feature importances.")

Feature Importances: [0.03971174 0.0491774  0.14642942 0.31836722 0.14104055 0.01676884
 0.04181785 0.01007986 0.01004418 0.04295358 0.01640581 0.03374578
 0.04285052 0.08048464 0.0101226 ]


In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Conv2D, Flatten, Dense, Dropout, Reshape
from keras.utils import to_categorical

# Assuming 'train' DataFrame has all the required features and 'appliance' as target
# Features are:
# 'info1', 'info2', 'year', 'month', 'day', 'hour', 'day_of_week',
# 'hour_sin', 'hour_cos', 'day_of_week_sin', 'day_of_week_cos',
# 'info1_lag_1', 'info2_lag_1', 'info1_rolling_mean_3', 'info2_rolling_std_3'

# Prepare input features and target variable
X = train[['info1', 'info2', 'year', 'month', 'day', 'hour', 'day_of_week',
           'hour_sin', 'hour_cos', 'day_of_week_sin', 'day_of_week_cos',
           'info1_lag_1', 'info2_lag_1', 'info1_rolling_mean_3', 'info2_rolling_std_3']].values
y = train['appliance'].values

# One-hot encode target variable
y_encoded = to_categorical(y)

# Normalize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Reshape data for CNN (samples, height, width, channels)
# Here, let's reshape into (5, 3) grid for example or any shape compatible with Conv2D
X_reshaped = X_scaled.reshape(X_scaled.shape[0], 5, 3, 1)  # 5x3 input with 1 channel

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_encoded, test_size=0.2, random_state=42)

# Build the CNN model
model = Sequential()

# Add a 2D convolutional layer
model.add(Conv2D(32, (2, 2), activation='relu', input_shape=(5, 3, 1)))  # Adjust kernel size as needed
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu'))
model.add(Dense(y_encoded.shape[1], activation='softmax'))  # Output layer

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=16, validation_data=(X_test, y_test))

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy * 100:.2f}%')


ModuleNotFoundError: No module named 'tensorflow'

In [26]:
!pip install tensorflow

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow


In [28]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2'],
}

random_search = RandomizedSearchCV(RandomForestClassifier(random_state=42),
                                   param_distributions=param_dist,
                                   n_iter=50,  # number of parameter settings sampled
                                   cv=3,
                                   verbose=1,
                                   n_jobs=-1,  # use all available cores
                                   random_state=42)

random_search.fit(X_train, y_train)
best_model = random_search.best_estimator_

Fitting 3 folds for each of 50 candidates, totalling 150 fits


MemoryError: Unable to allocate 15.7 MiB for an array with shape (4106093, 1) and data type int32

In [38]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Prepare input features and target variable
X = train[['info1', 'info2', 'year', 'month', 'day', 'hour', 'day_of_week',
           'hour_sin', 'hour_cos', 'day_of_week_sin', 'day_of_week_cos',
           'info1_lag_1', 'info2_lag_1', 'info1_rolling_mean_3', 'info2_rolling_std_3']].values
y = train['appliance'].values  # Target remains as integers (0 to 4)

# Normalize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Initialize and train the Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

# Display additional metrics
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Test Accuracy: 86.54%

Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.89      0.77    405067
           1       0.92      0.93      0.92   1143238
           2       0.89      0.84      0.87    679983
           3       0.94      0.59      0.73    235368

    accuracy                           0.87   2463656
   macro avg       0.86      0.81      0.82   2463656
weighted avg       0.88      0.87      0.87   2463656


Confusion Matrix:
 [[ 360611   16999   25779    1678]
 [  58450 1060166   22474    2148]
 [  71386   32134  572087    4376]
 [  35513   40970   19594  139291]]
